# Generated by Django 5.2.3 on 2025-07-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kanban_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Board",
                "verbose_name_plural": "Boards",
            },
        ),
        migrations.AlterModelOptions(
            name="boardmembership",
            options={
                "verbose_name": "Board Membership",
                "verbose_name_plural": "Board Memberships",
            },
        ),
        migrations.AlterModelOptions(
            name="column",
            options={
                "ordering": ["position"],
                "verbose_name": "Column",
                "verbose_name_plural": "Columns",
            },
        ),
    ]
