# Generated by Django 5.2.3 on 2025-07-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kanban_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="column",
            old_name="name",
            new_name="title",
        ),
    ]
