# Generated by Django 5.2.3 on 2025-07-11 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban_app", "0002_column_created_at_column_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardmembership",
            options={
                "verbose_name": "Board Membership",
                "verbose_name_plural": "Board Memberships",
            },
        ),
        migrations.RemoveField(
            model_name="column",
            name="title",
        ),
        migrations.AddField(
            model_name="column",
            name="name",
            field=models.CharField(default="Untitled Column", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="boardmembership",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kanban_app.board"
            ),
        ),
        migrations.AlterField(
            model_name="boardmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("EDITOR", "Editor"),
                    ("VIEWER", "Viewer"),
                ],
                default="VIEWER",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="boardmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="column",
            name="position",
            field=models.IntegerField(),
        ),
    ]
