# Generated by Django 5.2.3 on 2025-07-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kanban_app",
            "0002_alter_board_options_alter_boardmembership_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="deadline",
            field=models.DateTimeField(
                blank=True, help_text="Board deadline", null=True
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "Planning"),
                    ("ACTIVE", "Active"),
                    ("ON_HOLD", "On Hold"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PLANNING",
                max_length=20,
            ),
        ),
    ]
