# Generated by Django 5.2.3 on 2025-07-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "kanban_app",
            "0003_alter_boardmembership_options_remove_column_title_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="column",
            old_name="name",
            new_name="title",
        ),
    ]
