# Generated by Django 5.2.3 on 2025-07-09 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["position", "created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("low", "Low"),
                    ("MEDIUM", "Medium"),
                    ("medium", "Medium"),
                    ("HIGH", "High"),
                    ("high", "High"),
                    ("URGENT", "Urgent"),
                    ("urgent", "Urgent"),
                ],
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "To Do"),
                    ("to-do", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("in-progress", "In Progress"),
                    ("REVIEW", "Review"),
                    ("review", "Review"),
                    ("DONE", "Done"),
                    ("done", "Done"),
                ],
                default="TODO",
                max_length=20,
            ),
        ),
    ]
