# Generated by Django 5.2.3 on 2025-07-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_app", "0002_remove_task_assigned_to_remove_task_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["position"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                ],
                default="TODO",
                max_length=20,
            ),
        ),
    ]
