# Generated by Django 5.2.3 on 2025-07-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_app", "0003_alter_comment_options_alter_task_options_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                blank=True, help_text="Task due date", null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("URGENT", "Urgent"),
                ],
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("REVIEW", "Review"),
                    ("DONE", "Done"),
                ],
                default="TODO",
                max_length=20,
            ),
        ),
    ]
