# Generated by Django 5.2.3 on 2025-07-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_app", "0003_alter_comment_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="created_by",
        ),
        migrations.RemoveField(
            model_name="task",
            name="position",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("to-do", "To-do"),
                    ("in-progress", "In-progress"),
                    ("review", "Review"),
                    ("done", "Done"),
                ],
                default="to-do",
                max_length=20,
            ),
        ),
    ]
