# Generated by Django 5.2.3 on 2025-08-13 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tasks_app",
            "0004_alter_task_options_rename_author_comment_created_by_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="reviewer",
        ),
        migrations.AddField(
            model_name="task",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewing_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
